interface TopicCodeMapping {
  [key: string]: string;
  customizing: string;
  grip: string;
  color: string;
  no_logo: string;
  safety: string;
  certification: string;
  heat: string;
  overcharge_prevention: string;
  overcurrent: string;
  service: string;
  insurance: string;
  "delivery/packaging/shipping": string;
  multiport: string;
  stand: string;
  attachment: string;
  charging: string;
  fast_charging: string;
  simultaneous_charging: string;
  low_power: string;
  wireless_charging: string;
  magsafe: string;
  display: string;
  remaining_display: string;
  charging_display: string;
  battery_charge_speed: string;
  battery_compatibility: string;
  battery_capacity: string;
  etc: string;
  carry_on: string;
  eco_friendly: string;
  accessories: string;
  case: string;
  satisfaction: string;
  product_satisfaction: string;
  price: string;
  service_satisfaction: string;
  shipping: string;
  delivery: string;
  refund: string;
  packaging: string;
  after_service: string;
  repair: string;
  exchange: string;
  inquiry: string;
  key: string;
  key_feel: string;
  sound: string;
  key_pressure: string;
  key_travel: string;
  keycap: string;
  key_switch: string;
  stabilizer: string;
  lubrication: string;
  design: string;
  material: string;
  backlight: string;
  shape: string;
  key_engraving: string;
  portability: string;
  weight: string;
  size: string;
  product_configuration: string;
  pouch: string;
  battery: string;
  manual: string;
  keycap_remover: string;
  keyboard_cover: string;
  cable: string;
  product_quality: string;
  durability: string;
  finish: string;
  performance: string;
  lifespan: string;
  compatibility: string;
  latency: string;
  power_consumption: string;
  convenience: string;
  wrist: string;
  key_layout: string;
  keyboard_height: string;
  connection: string;
  dongle: string;
  bluetooth: string;
  wired: string;
  function: string;
  multi_pairing: string;
  foldable: string;
  rapid_trigger: string;
}

const topicCodeMapper: TopicCodeMapping = {
  customizing: "커스터마이징",
  grip: "그립감",
  color: "색감",
  no_logo: "로고없음",
  safety: "안전",
  certification: "인증",
  heat: "발열",
  overcharge_prevention: "과충전방지",
  overcurrent: "과전류",
  service: "서비스",
  insurance: "보험",
  "delivery/packaging/shipping": "배송/포장/발송",
  multiport: "멀티포트",
  stand: "거치",
  attachment: "부착",
  charging: "충전",
  fast_charging: "고속충전",
  simultaneous_charging: "동시충전",
  low_power: "저전력",
  wireless_charging: "무선충전",
  magsafe: "맥세이프",
  display: "디스플레이",
  remaining_display: "잔량표시",
  charging_display: "충전표시",
  battery_charge_speed: "배터리충전속도",
  battery_compatibility: "배터리를충전하는호환성",
  battery_capacity: "배터리용량",
  etc: "기타",
  carry_on: "기내반입",
  eco_friendly: "친환경",
  accessories: "구성품",
  case: "케이스",
  satisfaction: "만족도",
  product_satisfaction: "제품만족도",
  price: "가격",
  service_satisfaction: "서비스만족도",
  shipping: "발송",
  delivery: "배송",
  refund: "환불",
  packaging: "포장",
  after_service: "AS",
  repair: "수리",
  exchange: "교환",
  inquiry: "문의",
  key: "키",
  key_feel: "키감",
  sound: "소리",
  key_pressure: "키압",
  key_travel: "통울림",
  keycap: "키캡",
  key_switch: "키축",
  stabilizer: "스테빌라이저",
  lubrication: "윤활",
  design: "디자인",
  material: "재질",
  backlight: "백라이트",
  shape: "외형",
  key_engraving: "키보드각인",
  portability: "휴대성",
  weight: "무게",
  size: "사이즈",
  product_configuration: "제품구성",
  pouch: "파우치",
  battery: "건전지",
  manual: "설명서",
  keycap_remover: "키캡리무버",
  keyboard_cover: "키보드커버",
  cable: "케이블",
  product_quality: "제품품질",
  durability: "내구성",
  finish: "마감",
  performance: "성능",
  lifespan: "수명",
  compatibility: "호환성",
  latency: "지연율",
  power_consumption: "소비전력",
  convenience: "편의성",
  wrist: "손목",
  key_layout: "키배열",
  keyboard_height: "키보드높이",
  connection: "연결방식",
  dongle: "동글",
  bluetooth: "블루투스",
  wired: "유선",
  function: "기능",
  multi_pairing: "다중페어링",
  foldable: "접이식",
  rapid_trigger: "래피드 트리거",
};

export { topicCodeMapper };